@startuml atender_cita_v2

skinparam style strictuml

autonumber

actor Doctor
participant "Frontend (Vistas R.A.S.A)" as UI
participant "Backend (Flask)" as Flask
database "Base de Datos (SQL)" as BD

note over Doctor,UI
El doctor accede desde
Inicio o Agenda Médica
end note

Doctor -> UI: Selecciona paciente

activate UI

UI -> Flask: Consultar cita asignada

activate Flask

Flask -> BD: Buscar cita del paciente

activate BD

BD --> Flask: Estado de la cita

deactivate BD

alt No existe cita

    Flask --> UI: Paciente sin cita registrada

    UI --> Doctor: No es posible iniciar consulta

else Estado = Programada

    Flask --> UI: Check-in pendiente

    UI --> Doctor: Esperar recepción

else Estado = Pagada

    Flask --> UI: Check-in pendiente

    UI --> Doctor: Paciente aún no está en sala de espera

else Estado = En Espera

    Flask --> UI: Consulta autorizada

    UI --> Doctor: Puede abrir expediente

else Estado = En Consulta

    Flask --> UI: Consulta ya iniciada

    UI --> Doctor: Continuar consulta

else Estado = Completada

    Flask --> UI: Consulta finalizada

    UI --> Doctor: Solo lectura

else Estado = Cancelada

    Flask --> UI: Cita cancelada

    UI --> Doctor: No disponible

end


alt Estado = En Espera o En Consulta

    UI -> Flask: Solicitar expediente

    Flask -> BD: Obtener historial clínico

    activate BD

    BD --> Flask: Expediente completo

    deactivate BD

    Flask -> BD: Actualizar cita a En Consulta

    activate BD

    BD --> Flask: Actualización exitosa

    deactivate BD

    Flask --> UI: Mostrar expediente

    UI --> Doctor: Visualiza historial clínico

end

Doctor -> UI: Generar Nueva Receta

UI --> Doctor: Mostrar formulario médico

Doctor -> UI: Capturar diagnóstico

Doctor -> UI: Capturar tratamiento

Doctor -> UI: Capturar observaciones

Doctor -> UI: Agregar medicamentos

UI -> UI: Actualizar vista previa

Doctor -> UI: Guardar e Imprimir

UI -> Flask: Registrar consulta

note right of Flask

  Consulta Médica

  1. Guardar nota médica.
  2. Guardar receta.
  3. Asociar medicamentos.
  4. Marcar cita como Completada.

end note

Flask -> BD: Iniciar transacción

activate BD

Flask -> BD: Insertar consulta

Flask -> BD: Insertar medicamentos

Flask -> BD: Registrar receta

Flask -> BD: Actualizar cita a Completada

alt Operación exitosa

    Flask -> BD: Confirmar transacción

    BD --> Flask: Consulta guardada

else Error

    Flask -> BD: Cancelar transacción

    BD --> Flask: Error

    Flask --> UI: Error al guardar consulta

    UI --> Doctor: Intente nuevamente

end

deactivate BD

Flask -> Flask: Generar PDF de receta

Flask --> UI: URL del PDF

deactivate Flask

UI -> UI: Abrir PDF

UI -> UI: Ejecutar impresión

UI --> Doctor: Consulta finalizada

deactivate UI

@enduml