USE CentroMedicoRASA;

SELECT * FROM usuario;

SELECT * FROM EMPLEADO;

SELECT * FROM HORARIO;

SELECT * FROM DOCTOR ORDER BY Id_doctor DESC;

SELECT Id_usuario FROM EMPLEADO;

SELECT * FROM ESPECIALIDAD;

SELECT * FROM CITA
